#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-retrofit
Version  : 2.4.0
Release  : 1
URL      : https://github.com/square/retrofit/archive/parent-2.4.0.tar.gz
Source0  : https://github.com/square/retrofit/archive/parent-2.4.0.tar.gz
Source1  : https://repo1.maven.org/maven2/com/squareup/retrofit2/converter-moshi/2.4.0/converter-moshi-2.4.0.jar
Source2  : https://repo1.maven.org/maven2/com/squareup/retrofit2/converter-moshi/2.4.0/converter-moshi-2.4.0.pom
Source3  : https://repo1.maven.org/maven2/com/squareup/retrofit2/parent/2.4.0/parent-2.4.0.pom
Source4  : https://repo1.maven.org/maven2/com/squareup/retrofit2/retrofit-converters/2.4.0/retrofit-converters-2.4.0.pom
Source5  : https://repo1.maven.org/maven2/com/squareup/retrofit2/retrofit/2.4.0/retrofit-2.4.0.jar
Source6  : https://repo1.maven.org/maven2/com/squareup/retrofit2/retrofit/2.4.0/retrofit-2.4.0.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-retrofit-data = %{version}-%{release}
Requires: mvn-retrofit-license = %{version}-%{release}
BuildRequires : apache-maven
BuildRequires : buildreq-mvn

%description
Retrofit
========
Type-safe HTTP client for Android and Java by Square, Inc.
For more information please see [the website][1].

%package data
Summary: data components for the mvn-retrofit package.
Group: Data

%description data
data components for the mvn-retrofit package.


%package license
Summary: license components for the mvn-retrofit package.
Group: Default

%description license
license components for the mvn-retrofit package.


%prep
%setup -q -n retrofit-parent-2.4.0

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-retrofit
cp LICENSE.txt %{buildroot}/usr/share/package-licenses/mvn-retrofit/LICENSE.txt
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/squareup/retrofit2/converter-moshi/2.4.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/squareup/retrofit2/converter-moshi/2.4.0/converter-moshi-2.4.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/squareup/retrofit2/converter-moshi/2.4.0
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/squareup/retrofit2/converter-moshi/2.4.0/converter-moshi-2.4.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/squareup/retrofit2/parent/2.4.0
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/com/squareup/retrofit2/parent/2.4.0/parent-2.4.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/squareup/retrofit2/retrofit-converters/2.4.0
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/com/squareup/retrofit2/retrofit-converters/2.4.0/retrofit-converters-2.4.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/squareup/retrofit2/retrofit/2.4.0
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/com/squareup/retrofit2/retrofit/2.4.0/retrofit-2.4.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/squareup/retrofit2/retrofit/2.4.0
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/com/squareup/retrofit2/retrofit/2.4.0/retrofit-2.4.0.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/squareup/retrofit2/converter-moshi/2.4.0/converter-moshi-2.4.0.jar
/usr/share/java/.m2/repository/com/squareup/retrofit2/converter-moshi/2.4.0/converter-moshi-2.4.0.pom
/usr/share/java/.m2/repository/com/squareup/retrofit2/parent/2.4.0/parent-2.4.0.pom
/usr/share/java/.m2/repository/com/squareup/retrofit2/retrofit-converters/2.4.0/retrofit-converters-2.4.0.pom
/usr/share/java/.m2/repository/com/squareup/retrofit2/retrofit/2.4.0/retrofit-2.4.0.jar
/usr/share/java/.m2/repository/com/squareup/retrofit2/retrofit/2.4.0/retrofit-2.4.0.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-retrofit/LICENSE.txt
